name: "Generate"
description: "Generate files using XeLaTeX in a Docker container"
inputs:
  file:
    description: "File to process"
    required: true
  working-directory:
    description: "Working directory"
    required: true
    default: "."
runs:
  using: docker
  image: ghcr.io/maxa-ondrej/4iz232-umela-inteligence:xelatex
  env:
    WORKING_DIR: ${{ inputs.working-directory }}
  args:
    - ${{ inputs.file }}
