@startuml

title Knihy - Ontologie
    
class "Kniha" {
    - název: string
    - hodnocení: decimal
    - "rok vydaní": year
}

class "TištěnáKniha" {
    - "počet stran": integer
}
Kniha <|-- "TištěnáKniha"
() "Zaklínač1:PosledníPřání"
"TištěnáKniha" ..> "Zaklínač1:PosledníPřání"


class "Audiokniha" {
    - délka: decimal
}
Kniha <|-- "Audiokniha"

class "E-kniha" {
    - velikost: decimal
}
Kniha <|-- "E-kniha"

class "Osoba" {
    - věk: integer
}

class "Čtenář"
Osoba <|-- "Čtenář"
"Čtenář" --> "Kniha" : čteKnihu >
() "PetrMetr"
"Čtenář" ..> "PetrMetr"
"PetrMetr" --> "Zaklínač1:PosledníPřání" : čteKnihu >

class "Autor"
Osoba <|-- "Autor"
"Autor" --> "Kniha" : napsalKnihu >
() "AndrzejSapkowski"
"Autor" ..> "AndrzejSapkowski"
"AndrzejSapkowski" --> "Zaklínač1:PosledníPřání" : napsalKnihu >

class "Edice" {
    - ISBN: string
}
"Kniha" --> "Edice" : máEdici >

class "Formát"
"Kniha" --> "Formát" : máFormát >
() "TištěnýFormát"
"Formát" ..> "TištěnýFormát"
"Zaklínač1:PosledníPřání" --> "TištěnýFormát" : máFormát >
() "ElektronickýFormát"
"Formát" ..> "ElektronickýFormát"
() "AudioFormát"
"Formát" ..> "AudioFormát"

class "Jazyk"
"Kniha" --> "Jazyk" : jeVJazyce >
() "Čeština"
"Jazyk" ..> "Čeština"
"Zaklínač1:PosledníPřání" --> "Čeština" : jeVJazyce >
() "Angličtina"
"Jazyk" ..> "Angličtina"

class "Knihovna"
"Kniha" --> "Knihovna" : jeSoučástíKnihovny >
class "DatabázeAudioknih"
Knihovna <|-- "DatabázeAudioknih"
class "E-shop"
Knihovna <|-- "E-shop"
class "KamennáProdejna"
Knihovna <|-- "KamennáProdejna"
() "KnihyDobrovskýHavlíčkova"
"Knihovna" ..> "KnihyDobrovskýHavlíčkova"
"Zaklínač1:PosledníPřání" --> "KnihyDobrovskýHavlíčkova" : jeSoučástíKnihovny >

class "Žánr"
"Kniha" --> "Žánr" : máŽánr >
() "Fantasy"
"Žánr" ..> "Fantasy"
() "Sci-fi"
"Žánr" ..> "Sci-fi"
() "Romantika"
"Žánr" ..> "Romantika"

class "ObdobíVydání"
"Kniha" --> "ObdobíVydání" : jeVydánaVObdobí >
() "Klasicismus"
"ObdobíVydání" ..> "Klasicismus"
() "Postmoderna"
"ObdobíVydání" ..> "Postmoderna"
() "SoučasnáLiteratura"
"ObdobíVydání" ..> "SoučasnáLiteratura"
"Zaklínač1:PosledníPřání" --> "SoučasnáLiteratura" : jeVydánaVObdobí >

class "Série"
"Kniha" --> "Série" : jeSoučástíSérie >
class "Vydavatelství"
"Vydavatelství" --> "Kniha" : vydaloKnihu >

@enduml