@startuml

title Knihy - Ontologie
    
class "Kniha" {
    - název: string
    - hodnocení: decimal
    - "rok vydaní": year
}

class "Tištěná_kniha" {
    - "počet stran": integer
}
Kniha <|-- "Tištěná_kniha"
() "Zaklínač_1:_poslední_přání"
"Tištěná_kniha" ..> "Zaklínač_1:_poslední_přání"


class "Audiokniha" {
    - délka: decimal
}
Kniha <|-- "Audiokniha"

class "E-kniha" {
    - velikost: decimal
}
Kniha <|-- "E-kniha"

class "Osoba" {
    - věk: integer
}

class "Čtenář"
Osoba <|-- "Čtenář"
"Čtenář" --> "Kniha" : čteKnihu >
() "PetrMetr"
"Čtenář" ..> "PetrMetr"
"PetrMetr" --> "Zaklínač_1:_poslední_přání" : čteKnihu >

class "Autor"
Osoba <|-- "Autor"
"Autor" --> "Kniha" : napsalKnihu >
() "Andrzej_Sapkowski"
"Autor" ..> "Andrzej_Sapkowski"
"Andrzej_Sapkowski" --> "Zaklínač_1:_poslední_přání" : napsalKnihu >

class "Edice" {
    - ISBN: string
}
"Kniha" --> "Edice" : máEdici >

class "Formát"
"Kniha" --> "Formát" : máFormát >
() "TištěnýFormát"
"Formát" ..> "TištěnýFormát"
"Zaklínač_1:_poslední_přání" --> "TištěnýFormát" : máFormát >
() "ElektronickýFormát"
"Formát" ..> "ElektronickýFormát"
() "AudioFormát"
"Formát" ..> "AudioFormát"

class "Jazyk"
"Kniha" --> "Jazyk" : jeVJazyce >
() "Čeština"
"Jazyk" ..> "Čeština"
"Zaklínač_1:_poslední_přání" --> "Čeština" : jeVJazyce >
() "Angličtina"
"Jazyk" ..> "Angličtina"

class "Knihovna"
"Kniha" --> "Knihovna" : jeSoučástíKnihovny >
class "Databáze_audioknih"
Knihovna <|-- "Databáze_audioknih"
class "E-shop"
Knihovna <|-- "E-shop"
class "Kamenná_prodejna"
Knihovna <|-- "Kamenná_prodejna"
() "Knihy_Dobrovský_Havlíčkova"
"Knihovna" ..> "Knihy_Dobrovský_Havlíčkova"
"Zaklínač_1:_poslední_přání" --> "Knihy_Dobrovský_Havlíčkova" : jeSoučástíKnihovny >

class "Žánr"
"Kniha" --> "Žánr" : máŽánr >
() "Fantasy"
"Žánr" ..> "Fantasy"
() "Sci-fi"
"Žánr" ..> "Sci-fi"
() "Romantika"
"Žánr" ..> "Romantika"

class "Období_vydání"
"Kniha" --> "Období_vydání" : jeVydánaVObdobí >
class "90_léta"
"Období_vydání" <|-- "90_léta"
() "1990"
"90_léta" ..> "1990"
() "1991"
"90_léta" ..> "1991"
() "1992"
"90_léta" ..> "1992"
() "1993"
"90_léta" ..> "1993"
"Zaklínač_1:_poslední_přání" --> "1993" : jeVydánaVObdobí >

class "Série"
"Kniha" --> "Série" : jeSoučástíSérie >
class "Vydavatelství"
"Vydavatelství" --> "Kniha" : vydaloKnihu >

@enduml