name: "Generate"
description: "Generate files using XeLaTeX in a Docker container"
inputs:
  files:
    description: "Files to process"
    required: true
  output-dir:
    description: "Output directory"
    required: true
    default: "."
runs:
  using: docker
  image: ghcr.io/maxa-ondrej/4iz232-umela-inteligence:plantuml
  args:
    - -tpng
    - --output-dir ${{ inputs.output-dir }}
    - ${{ inputs.files }}
