name: "Generate"
description: "Generate files using XeLaTeX in a Docker container"
inputs:
  files:
    description: "Files to process"
    required: true
  working-directory:
    description: "Working directory"
    required: true
    default: "."
  charset:
    description: "Character set"
    required: false
    default: "UTF-8"
runs:
  using: docker
  image: ghcr.io/maxa-ondrej/4iz232-umela-inteligence:plantuml
  env:
    WORKING_DIR: ${{ inputs.working-directory }}
  args:
    - -tpng
    - -charset ${{ inputs.charset }}
    - ${{ inputs.files }}
