name: "Generate"
description: "Generate files using XeLaTeX in a Docker container"
inputs:
  file:
    description: "File to process"
    required: true
  working-directory:
    description: "Working directory to run the command in"
    required: true
    default: "."
runs:
  using: composite
  steps:
    - name: "Prepare XeLaTeX"
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update -y
        sudo apt-get install -y git wget openjdk-17-jre graphviz pandoc texlive librsvg2-bin build-essential
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra texlive-xetex
    - name: "Generate file with XeLaTeX"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: xelatex ${{ inputs.file }}
