name: "Generate"
description: "Generate files using XeLaTeX in a Docker container"
inputs:
  file:
    description: "File to process"
    required: true
outputs:
  file:
    description: "The processed file"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - xelatex
    - ${{ inputs.file }}
