name: Build

on:
  push:
    branches:
      - main

jobs:
  protege:
    name: Protege
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PROJECT: protege
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions
            ${{ env.PROJECT }}

      - name: Generate UML Diagrams
        uses: ./.github/actions/plantuml
        with:
          files: ./*.puml
          working-directory: ${{ env.PROJECT }}/analyza

      - name: Generate Referat
        uses: ./.github/actions/xelatex
        with:
          file: referat.tex
          working-directory: ${{ env.PROJECT }}

      - name: Generate Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT }}
          path: |
            ${{ env.PROJECT }}/**/*.png
            ${{ env.PROJECT }}/**/*.jpg
            ${{ env.PROJECT }}/**/*.txt
            ${{ env.PROJECT }}/**/*.pdf
            ${{ env.PROJECT }}/**/*.owl
            ${{ env.PROJECT }}/**/*.rdf
