name: Build

on:
  push:
    branches:
      - main

jobs:
  protege:
    name: Protege
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./protege
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate UML Diagrams
        uses: ./.github/actions/plantuml
        with:
          files: ./*.puml
          working-directory: ./protege/analyza

      - name: Generate Referat
        uses: ./.github/actions/xelatex
        with:
          file: referat.tex
          working-directory: ./protege

      - name: Generate Artifact
        uses: actions/upload-artifact@v4
        with:
          name: protege
          path: |
            protege/**/*.png
            protege/**/*.jpg
            protege/**/*.txt
            protege/**/*.pdf
            protege/**/*.owl
            protege/**/*.rdf
